language: java
jdk:
  - openjdk11

branches:
  only:
    - master
    - "/^v[0-9]+\\.[0-9]+/"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings travis-settings.xml

cache:
  directories:
    - '$HOME/.m2/repository'
